
permalink: /:year/:month/:day/:title.html
name: "YangYang0477"


author: "Orods小羊"
highlighter: pygments
encoding: utf-8

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: BlogLink
    class: fa fa-link
    href: /links.html
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

