
permalink: /:year/:month/:day/:title.html
name: "YangYang0477"
markdown: kramdown
favicon: "/favicon.ico"
author: "Orods杨阳"
url: "http://yangyang0477.github.io"
highlighter: rouge
encoding: utf-8

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Code
    class: fa fa-file
    href: /code.html
  - title: BlogLink
    class: fa fa-link
    href: /links.html		
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml		

